name: Build & Deploy All

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [data_ingestion, data_transformation, model_training, model_serving]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image
        env:
          COMPONENT: ${{ matrix.component }}
        run: |
          ECR_REPO="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com"
          IMAGE_NAME="${ECR_REPO}/${COMPONENT}:latest"
          docker build -t $IMAGE_NAME ./docker/$COMPONENT
          docker push $IMAGE_NAME

      - name: Deploy via Helm
        run: |
          helm upgrade --install ${{ matrix.component }} ./helm/mlops-app \
            --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.component }} \
            --set image.tag=latest
