adminPassword: admin
service:
  type: LoadBalancer

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    mlflow:
      file: /var/lib/grafana/dashboards/default/mlflow.json
    kserve:
      file: /var/lib/grafana/dashboards/default/kserve.json
    system-metrics:
      file: /var/lib/grafana/dashboards/default/system-metrics.json

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
