AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB Sessions Table for Bedrock multi-tenant cost tracking

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]

  ResourceNamePrefix:
    Type: String
    Default: bedrock-cost-tracking

Resources:
  # Sessions Table
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ResourceNamePrefix}-${Environment}-sessions"
      BillingMode: PAY_PER_REQUEST
      
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: tenantId
          AttributeType: S

      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: TenantIndex
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BedrockCostTracking
        - Key: Component
          Value: SessionsTable

Outputs:
  SessionsTableName:
    Description: Sessions table name
    Value: !Ref SessionsTable
    Export:
      Name: !Sub "${ResourceNamePrefix}-${Environment}-sessions-table-name"

  SessionsTableArn:
    Description: Sessions table ARN
    Value: !GetAtt SessionsTable.Arn
    Export:
      Name: !Sub "${ResourceNamePrefix}-${Environment}-sessions-table-arn"
