apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: your_aws_access_key
  AWS_SECRET_ACCESS_KEY: your_aws_secret_key
  AWS_DEFAULT_REGION: your_region
