apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
type: Opaque
stringData:
  MLFLOW_S3_ENDPOINT_URL: http://your-s3-endpoint
  AWS_ACCESS_KEY_ID: your_aws_access_key
  AWS_SECRET_ACCESS_KEY: your_aws_secret_key
  BACKEND_STORE_URI: postgresql://user:pass@postgres:5432/mlflow
  ARTIFACT_ROOT: s3://my_bucket/mlflow/
