# 定义使用的模型名称，这里使用的是Hugging Face提供的预训练模型
MODEL_NAME = "distilbert-base-uncased"

# 定义医学领域分类列表，涵盖了各种医学专业和领域
MEDICAL_CATEGORIES = [
    " Allergy / Immunology",
    " Autopsy",
    " Bariatrics",
    " Cardiovascular / Pulmonary",
    " Chiropractic",
    " Consult - History and Phy.",
    " Cosmetic / Plastic Surgery",
    " Dentistry",
    " Dermatology",
    " Diets and Nutritions",
    " Discharge Summary",
    " ENT - Otolaryngology",
    " Emergency Room Reports",
    " Endocrinology",
    " Gastroenterology",
    " General Medicine",
    " Hematology - Oncology",
    " Hospice - Palliative Care",
    " IME-QME-Work Comp etc.",
    " Lab Medicine - Pathology",
    " Letters",
    " Nephrology",
    " Neurology",
    " Neurosurgery",
    " Obstetrics / Gynecology",
    " Office Notes",
    " Ophthalmology",
    " Orthopedic",
    " Pain Management",
    " Pediatrics - Neonatal",
    " Physical Medicine - Rehab",
    " Podiatry",
    " Psychiatry / Psychology",
    " Radiology",
    " Rheumatology",
    " SOAP / Chart / Progress Notes",
    " Sleep Medicine",
    " Speech - Language",
    " Surgery",
    " Urology",
]
