apiVersion: batch/v1
kind: Job
metadata:
  name: train-model
spec:
  template:
    spec:
      containers:
        - name: train
          image: <your_ecr_repo>/model-training:latest
          envFrom:
            - secretRef:
                name: aws-secrets
            - secretRef:
                name: mlflow-secrets
      restartPolicy: Never
